version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/vivuplan-be:latest
    container_name: vivuplan-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - server.port=8080
